# Generated by Django 4.2.4 on 2023-08-02 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdrental', '0003_rename_rental_id_renewal_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='renewal_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
