# Generated by Django 4.2.4 on 2023-08-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dvdrental', '0004_alter_renewal_renewal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(primary_key=True, serialize=False),
        ),
    ]
